### ISSUE TITLE
The script stopped working :  KeyError: 'data'

### ISSUE THREAD

**Issue by proabiral** [defparam/h1passets#8]
Thank you for the tool.

Seems like there has been some change in the API from Hackerone, causing the script to crash.

![image](https://user-images.githubusercontent.com/22173232/119994230-20e50880-bfec-11eb-85ee-045856ab782f.png)

Hope you can take a look at it.

**Comment by jthack** [comment]
New api was rolled out :(

**Comment by jthack** [comment]
I think I fixed it: https://github.com/defparam/h1passets/pull/9

**Comment by defparam** [comment]
Thanks! I made a small change to the query. One of the keys is no longer used and wasn't used in my script anyway. Try it out now should be fixed
